-- [F-002] move_npc_races: characterfacialhairstyles
-- Reintroduces Fel Orc entries as race 32, Naga as 33, etc.

DELETE FROM `characterfacialhairstyles` WHERE `race` IN (12, 13, 14, 15, 16, 17, 18, 19, 20, 21); -- for lack of an ID field
DELETE FROM `characterfacialhairstyles` WHERE `race` = 32 AND `gender` = 0 AND `variation_id` = 0;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (32, 0, 0, 0, 0, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 32 AND `gender` = 1 AND `variation_id` = 0;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (32, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 33 AND `gender` = 0 AND `variation_id` = 0;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (33, 0, 0, 0, 0, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 33 AND `gender` = 1 AND `variation_id` = 0;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (33, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 34 AND `gender` = 1 AND `variation_id` = 0;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (34, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 35 AND `gender` = 0 AND `variation_id` = 0;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (35, 0, 0, 0, 0, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 35 AND `gender` = 1 AND `variation_id` = 0;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (35, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 36 AND `gender` = 0 AND `variation_id` = 0;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (36, 0, 0, 0, 0, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 36 AND `gender` = 1 AND `variation_id` = 0;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (36, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 36 AND `gender` = 0 AND `variation_id` = 1;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (36, 0, 1, 2, 0, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 36 AND `gender` = 0 AND `variation_id` = 2;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (36, 0, 2, 3, 0, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 36 AND `gender` = 0 AND `variation_id` = 3;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (36, 0, 3, 4, 0, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 36 AND `gender` = 0 AND `variation_id` = 4;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (36, 0, 4, 5, 0, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 36 AND `gender` = 0 AND `variation_id` = 5;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (36, 0, 5, 6, 0, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 37 AND `gender` = 0 AND `variation_id` = 6;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (37, 0, 6, 8, 0, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 37 AND `gender` = 1 AND `variation_id` = 0;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (37, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 37 AND `gender` = 0 AND `variation_id` = 1;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (37, 0, 1, 3, 0, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 37 AND `gender` = 0 AND `variation_id` = 2;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (37, 0, 2, 4, 0, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 37 AND `gender` = 0 AND `variation_id` = 0;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (37, 0, 0, 2, 0, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 37 AND `gender` = 0 AND `variation_id` = 4;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (37, 0, 4, 6, 0, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 37 AND `gender` = 0 AND `variation_id` = 3;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (37, 0, 3, 5, 0, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 37 AND `gender` = 0 AND `variation_id` = 5;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (37, 0, 5, 7, 0, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 38 AND `gender` = 0 AND `variation_id` = 3;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (38, 0, 3, 0, 5, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 38 AND `gender` = 1 AND `variation_id` = 0;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (38, 1, 0, 0, 0, 0, -858993460, -858993460);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 38 AND `gender` = 0 AND `variation_id` = 0;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (38, 0, 0, 0, 2, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 38 AND `gender` = 0 AND `variation_id` = 10;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (38, 0, 10, 0, 4, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 38 AND `gender` = 0 AND `variation_id` = 1;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (38, 0, 1, 0, 3, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 38 AND `gender` = 0 AND `variation_id` = 2;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (38, 0, 2, 0, 4, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 38 AND `gender` = 0 AND `variation_id` = 4;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (38, 0, 4, 0, 6, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 38 AND `gender` = 0 AND `variation_id` = 5;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (38, 0, 5, 0, 2, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 38 AND `gender` = 0 AND `variation_id` = 6;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (38, 0, 6, 0, 3, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 38 AND `gender` = 0 AND `variation_id` = 7;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (38, 0, 7, 0, 4, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 38 AND `gender` = 0 AND `variation_id` = 8;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (38, 0, 8, 0, 5, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 38 AND `gender` = 0 AND `variation_id` = 9;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (38, 0, 9, 0, 6, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 39 AND `gender` = 1 AND `variation_id` = 0;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (39, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 39 AND `gender` = 0 AND `variation_id` = 0;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (39, 0, 0, 2, 0, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 39 AND `gender` = 0 AND `variation_id` = 1;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (39, 0, 1, 3, 0, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 39 AND `gender` = 0 AND `variation_id` = 2;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (39, 0, 2, 4, 0, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 40 AND `gender` = 0 AND `variation_id` = 1;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (40, 0, 1, 1, 0, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 40 AND `gender` = 1 AND `variation_id` = 0;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (40, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 40 AND `gender` = 0 AND `variation_id` = 2;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (40, 0, 2, 2, 0, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 40 AND `gender` = 0 AND `variation_id` = 3;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (40, 0, 3, 3, 0, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 40 AND `gender` = 0 AND `variation_id` = 4;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (40, 0, 4, 4, 0, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 40 AND `gender` = 0 AND `variation_id` = 0;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (40, 0, 0, 0, 0, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 41 AND `gender` = 0 AND `variation_id` = 0;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (41, 0, 0, 0, 2, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 41 AND `gender` = 1 AND `variation_id` = 0;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (41, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 41 AND `gender` = 0 AND `variation_id` = 1;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (41, 0, 1, 0, 3, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 41 AND `gender` = 0 AND `variation_id` = 2;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (41, 0, 2, 0, 4, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 41 AND `gender` = 0 AND `variation_id` = 3;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (41, 0, 3, 0, 5, 0, 0, 0);
DELETE FROM `characterfacialhairstyles` WHERE `race` = 41 AND `gender` = 0 AND `variation_id` = 4;
INSERT INTO `characterfacialhairstyles` (`race`, `gender`, `variation_id`, `geoset_1`, `geoset_2`, `geoset_3`, `geoset_4`, `geoset_5`) VALUES (41, 0, 4, 0, 6, 0, 0, 0);
