-- Legacy helper intentionally disabled.
-- Worgen riding / Running Wild is handled by src/Worgoblin.cpp and
-- lua_scripts/racials.lua. Keeping this file as a no-op prevents an old
-- installed copy from granting free riding when the module config disables it.
