-- [F-30] mod-worgoblin: charhairgeosets
-- Reintroduces Fel Orc entries as race 32, Naga as 33, etc.

DELETE FROM `charhairgeosets` WHERE `id` = 264;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (264, 32, 0, 0, 2, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 265;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (265, 32, 1, 0, 2, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 294;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (294, 33, 0, 0, 0, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 295;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (295, 33, 1, 0, 0, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 247;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (247, 34, 0, 0, 1, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 297;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (297, 34, 1, 0, 0, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 301;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (301, 34, 0, 1, 2, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 302;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (302, 34, 0, 2, 3, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 298;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (298, 35, 0, 0, 0, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 299;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (299, 35, 1, 0, 0, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 304;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (304, 36, 0, 2, 3, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 305;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (305, 36, 1, 0, 0, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 314;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (314, 36, 0, 0, 0, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 315;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (315, 36, 0, 1, 2, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 316;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (316, 36, 0, 3, 4, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 317;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (317, 36, 0, 4, 5, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 318;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (318, 36, 0, 5, 6, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 306;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (306, 37, 0, 6, 7, 1);
DELETE FROM `charhairgeosets` WHERE `id` = 307;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (307, 37, 1, 0, 0, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 327;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (327, 37, 0, 0, 1, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 328;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (328, 37, 0, 2, 3, 1);
DELETE FROM `charhairgeosets` WHERE `id` = 329;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (329, 37, 0, 3, 4, 1);
DELETE FROM `charhairgeosets` WHERE `id` = 330;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (330, 37, 0, 4, 5, 1);
DELETE FROM `charhairgeosets` WHERE `id` = 331;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (331, 37, 0, 1, 2, 1);
DELETE FROM `charhairgeosets` WHERE `id` = 332;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (332, 37, 0, 5, 6, 1);
DELETE FROM `charhairgeosets` WHERE `id` = 319;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (319, 38, 0, 0, 0, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 320;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (320, 38, 1, 0, 0, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 321;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (321, 38, 0, 1, 2, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 322;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (322, 38, 0, 2, 3, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 323;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (323, 38, 0, 3, 4, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 324;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (324, 38, 0, 4, 5, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 325;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (325, 38, 0, 5, 6, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 333;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (333, 39, 0, 0, 1, 1);
DELETE FROM `charhairgeosets` WHERE `id` = 334;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (334, 39, 1, 0, 0, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 435;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (435, 40, 0, 0, 0, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 436;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (436, 40, 1, 0, 0, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 438;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (438, 41, 1, 0, 0, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 439;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (439, 41, 0, 0, 0, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 440;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (440, 41, 0, 1, 2, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 441;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (441, 41, 0, 2, 3, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 442;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (442, 41, 0, 3, 4, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 443;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (443, 41, 0, 4, 5, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 444;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (444, 41, 0, 5, 6, 0);
