-- Gilnean race support

DELETE FROM `namegen` WHERE `id` = 19100;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19100, 'Agamand', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19101;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19101, 'Andromath', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19102;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19102, 'Antonidas', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19103;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19103, 'Fordred', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19104;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19104, 'Nielas', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19105;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19105, 'Nielas', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19106;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19106, 'Arius', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19107;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19107, 'Arugal', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19108;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19108, 'Sten', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19109;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19109, 'Ballador', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19110;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19110, 'Barthilas', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19111;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19111, 'Aedelas', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19112;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19112, 'Conjurus', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19113;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19113, 'Rex', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19114;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19114, 'Danath', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19115;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19115, 'Saidin', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19116;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19116, 'Dalar', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19117;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19117, 'Alonsus', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19118;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19118, 'Tenn', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19119;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19119, 'Tirion', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19120;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19120, 'Taelan', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19121;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19121, 'Gavinrad', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19122;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19122, 'Granis', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19123;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19123, 'Genn', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19124;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19124, 'Nandis', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19125;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19125, 'Geros', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19126;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19126, 'Jorn', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19127;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19127, 'Khadgar', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19128;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19128, 'Landazar', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19129;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19129, 'Shal', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19130;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19130, 'Anduin', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19131;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19131, 'Doril', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19132;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19132, 'Marn', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19133;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19133, 'Malak', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19134;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19134, 'Manadar', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19135;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19135, 'Medivh', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19136;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19136, 'Arthas', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19137;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19137, 'Terenas', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19138;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19138, 'Morlune', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19139;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19139, 'Moroes', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19140;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19140, 'Daelin', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19141;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19141, 'Rhonin', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19142;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19142, 'Sage', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19143;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19143, 'Duncan', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19144;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19144, 'Manos', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19145;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19145, 'Peril', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19146;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19146, 'Aran', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19147;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19147, 'Thoras', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19148;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19148, 'Turalyon', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19149;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19149, 'Uther', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19150;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19150, 'Varien', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19151;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19151, 'Llane', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19152;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19152, 'Zann', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19153;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19153, 'Aegwynn', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19154;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19154, 'Taretha', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19155;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19155, 'Calia', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19156;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19156, 'Maevis', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19157;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19157, 'Alexis', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19158;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19158, 'Ariandra', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19159;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19159, 'Kassandra', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19160;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19160, 'Wilhelmina', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19161;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19161, 'Gloriana', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19162;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19162, 'Sarah', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19163;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19163, 'Samantha', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19164;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19164, 'Kitiara', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19165;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19165, 'April', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19166;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19166, 'Jorune', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19167;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19167, 'Brunhilde', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19168;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19168, 'Sithaya', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19169;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19169, 'Andra', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19170;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19170, 'Amora', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19171;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19171, 'Dierdre', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19172;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19172, 'Sandris', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19173;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19173, 'Adelaide', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19174;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19174, 'Alice', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19175;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19175, 'Amaria', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19176;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19176, 'Amelia', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19177;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19177, 'Avelina', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19178;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19178, 'Barbara', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19179;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19179, 'Beatrix', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19180;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19180, 'Betta', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19181;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19181, 'Brigit', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19182;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19182, 'Calli', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19183;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19183, 'Candis', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19184;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19184, 'Carolyn', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19185;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19185, 'Catherine', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19186;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19186, 'Catin', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19187;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19187, 'Christiana', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19188;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19188, 'Christine', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19189;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19189, 'Cicely', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19190;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19190, 'Constance', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19191;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19191, 'Cristina', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19192;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19192, 'Dagny', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19193;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19193, 'Danielle', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19194;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19194, 'Darcy', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19195;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19195, 'Desiree', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19196;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19196, 'Felicity', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19197;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19197, 'Florencia', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19198;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19198, 'Giliana', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19199;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19199, 'Gladys', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19200;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19200, 'Grace', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19201;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19201, 'Heloise', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19202;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19202, 'Honor', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19203;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19203, 'Hope', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19204;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19204, 'Jane', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19205;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19205, 'Joy', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19206;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19206, 'Kaisa', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19207;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19207, 'Kamilla', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19208;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19208, 'Kimberly', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19209;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19209, 'Lia', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19210;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19210, 'Lois', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19211;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19211, 'Lola', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19212;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19212, 'Lucille', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19213;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19213, 'Margery', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19214;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19214, 'Marilyn', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19215;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19215, 'Marlena', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19216;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19216, 'Meghan', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19217;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19217, 'Mercy', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19218;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19218, 'Mirabell', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19219;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19219, 'Naomi', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19220;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19220, 'Pamela', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19221;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19221, 'Peggy', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19222;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19222, 'Prudence', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19223;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19223, 'Reyna', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19224;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19224, 'Rhoda', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19225;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19225, 'Sabeline', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19226;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19226, 'Theda', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19227;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19227, 'Thelma', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19228;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19228, 'Theresa', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19229;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19229, 'Tiffany', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19230;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19230, 'Tina', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19231;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19231, 'Tracy', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19232;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19232, 'Verity', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19233;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19233, 'Aimery', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19234;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19234, 'Alex', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19235;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19235, 'Alonso', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19236;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19236, 'Ander', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19237;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19237, 'Anselm', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19238;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19238, 'Apollo', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19239;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19239, 'Arlan', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19240;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19240, 'Benedict', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19241;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19241, 'Berenger', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19242;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19242, 'Bertren', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19243;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19243, 'Bruce', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19244;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19244, 'Carl', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19245;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19245, 'Carlin', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19246;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19246, 'Carter', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19247;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19247, 'Cedric', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19248;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19248, 'Clement', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19249;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19249, 'Clinton', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19250;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19250, 'Daniel', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19251;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19251, 'Darren', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19252;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19252, 'Derek', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19253;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19253, 'Eric', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19254;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19254, 'Errol', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19255;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19255, 'Everard', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19256;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19256, 'Garth', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19257;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19257, 'Geoff', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19258;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19258, 'Graham', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19259;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19259, 'Gregory', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19260;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19260, 'Guillaume', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19261;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19261, 'Hadrian', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19262;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19262, 'Halian', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19263;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19263, 'Harold', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19264;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19264, 'Isaac', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19265;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19265, 'Jack', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19266;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19266, 'Jacob', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19267;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19267, 'Jed', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19268;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19268, 'Jeff', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19269;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19269, 'Jeremiah', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19270;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19270, 'Jessie', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19271;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19271, 'Jethro', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19272;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19272, 'Johan', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19273;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19273, 'Judd', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19274;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19274, 'Leroy', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19275;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19275, 'Mitchell', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19276;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19276, 'Paul', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19277;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19277, 'Raiford', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19278;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19278, 'Reese', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19279;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19279, 'Regis', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19280;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19280, 'Reid', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19281;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19281, 'Robert', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19282;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19282, 'Rodney', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19283;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19283, 'Taylor', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19284;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19284, 'Thibault', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19285;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19285, 'Todd', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19286;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19286, 'Walter', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19287;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19287, 'Warin', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19288;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19288, 'Warren', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19289;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19289, 'Wayne', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19290;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19290, 'Wymon', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19291;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19291, 'Xander', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19292;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19292, 'Yves', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19293;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19293, 'Abelard', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19294;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19294, 'Adin', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19295;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19295, 'Adorian', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19296;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19296, 'Aiden', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19297;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19297, 'Aironus', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19298;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19298, 'Alden', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19299;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19299, 'Alexios', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19300;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19300, 'Anders', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19301;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19301, 'Anson', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19302;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19302, 'Artim', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19303;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19303, 'Ashton', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19304;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19304, 'Austen', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19305;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19305, 'Bailby', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19306;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19306, 'Barraud', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19307;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19307, 'Benes', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19308;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19308, 'Brayden', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19309;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19309, 'Caleb', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19310;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19310, 'Cayden', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19311;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19311, 'Cayne', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19312;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19312, 'Cedrick', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19313;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19313, 'Clark', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19314;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19314, 'Clayton', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19315;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19315, 'Corey', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19316;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19316, 'Curtis', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19317;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19317, 'Daician', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19318;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19318, 'Dallin', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19319;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19319, 'Damone', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19320;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19320, 'Davin', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19321;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19321, 'Devon', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19322;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19322, 'Dewey', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19323;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19323, 'Draven', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19324;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19324, 'Dyrius', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19325;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19325, 'Eames', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19326;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19326, 'Edward', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19327;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19327, 'Elgar', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19328;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19328, 'Elroy', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19329;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19329, 'Ethon', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19330;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19330, 'Fanley', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19331;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19331, 'Filmore', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19332;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19332, 'Fletcher', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19333;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19333, 'Franklin', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19334;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19334, 'Gage', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19335;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19335, 'Galan', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19336;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19336, 'Gannet', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19337;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19337, 'Gerrick', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19338;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19338, 'Gunnar', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19339;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19339, 'Haiden', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19340;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19340, 'Haldane', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19341;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19341, 'Halsey', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19342;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19342, 'Holden', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19343;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19343, 'Hudson', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19344;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19344, 'Iridian', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19345;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19345, 'Jaaron', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19346;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19346, 'Jairund', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19347;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19347, 'Jarek', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19348;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19348, 'Jayson', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19349;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19349, 'Jesse', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19350;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19350, 'Joel', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19351;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19351, 'Jonah', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19352;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19352, 'Jonathan', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19353;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19353, 'Justus', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19354;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19354, 'Kai', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19355;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19355, 'Kalvin', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19356;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19356, 'Karsh', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19357;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19357, 'Kashel', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19358;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19358, 'Kaylan', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19359;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19359, 'Keifer', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19360;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19360, 'Keion', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19361;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19361, 'Kenton', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19362;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19362, 'Kevyn', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19363;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19363, 'Koby', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19364;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19364, 'Korban', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19365;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19365, 'Kuthbert', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19366;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19366, 'Lamarre', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19367;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19367, 'Lars', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19368;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19368, 'Lashan', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19369;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19369, 'Layton', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19370;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19370, 'Leland', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19371;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19371, 'Maddox', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19372;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19372, 'Marius', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19373;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19373, 'Marlon', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19374;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19374, 'Miccah', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19375;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19375, 'Nathan', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19376;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19376, 'Nelson', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19377;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19377, 'Nolen', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19378;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19378, 'Oren', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19379;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19379, 'Padrik', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19380;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19380, 'Parker', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19381;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19381, 'Patrick', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19382;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19382, 'Payton', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19383;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19383, 'Phillip', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19384;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19384, 'Piotyr', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19385;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19385, 'Quin', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19386;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19386, 'Quincey', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19387;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19387, 'Sebastian', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19388;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19388, 'Silas', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19389;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19389, 'Symon', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19390;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19390, 'Tanner', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19391;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19391, 'Tavish', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19392;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19392, 'Theodore', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19393;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19393, 'Vale', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19394;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19394, 'Walton', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19395;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19395, 'Waylen', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19396;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19396, 'Willifred', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19397;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19397, 'Yancy', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19398;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19398, 'Yani', 23, 0);
DELETE FROM `namegen` WHERE `id` = 19399;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19399, 'Acacia', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19400;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19400, 'Alessandra', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19401;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19401, 'Amadria', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19402;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19402, 'Andraia', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19403;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19403, 'Annalea', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19404;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19404, 'Ardyth', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19405;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19405, 'Astradyn', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19406;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19406, 'Autumn', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19407;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19407, 'Becky', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19408;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19408, 'Blythe', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19409;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19409, 'Briar', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19410;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19410, 'Brylee', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19411;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19411, 'Callista', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19412;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19412, 'Cassandra', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19413;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19413, 'Cassima', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19414;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19414, 'Challie', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19415;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19415, 'Chana', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19416;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19416, 'Chelsea', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19417;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19417, 'Chiara', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19418;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19418, 'Dannison', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19419;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19419, 'Daphne', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19420;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19420, 'Darla', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19421;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19421, 'Deandra', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19422;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19422, 'Dellah', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19423;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19423, 'Dominique', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19424;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19424, 'Doriah', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19425;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19425, 'Dorothy', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19426;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19426, 'Edith', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19427;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19427, 'Elaina', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19428;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19428, 'Elenore', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19429;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19429, 'Emilee', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19430;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19430, 'Emma', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19431;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19431, 'Everette', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19432;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19432, 'Evie', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19433;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19433, 'Farrah', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19434;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19434, 'Fiorella', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19435;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19435, 'Galiya', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19436;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19436, 'Gillian', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19437;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19437, 'Gizela', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19438;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19438, 'Gracelyn', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19439;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19439, 'Heidie', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19440;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19440, 'Ilana', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19441;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19441, 'Ione', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19442;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19442, 'Jaimie', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19443;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19443, 'Jalissa', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19444;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19444, 'Janessa', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19445;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19445, 'Jinnea', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19446;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19446, 'Johanna', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19447;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19447, 'Jolanda', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19448;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19448, 'Jolene', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19449;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19449, 'Kaiah', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19450;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19450, 'Kaiya', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19451;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19451, 'Karleigh', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19452;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19452, 'Kelsea', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19453;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19453, 'Kirsten', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19454;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19454, 'Korla', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19455;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19455, 'Kyara', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19456;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19456, 'Leiah', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19457;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19457, 'Leliani', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19458;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19458, 'Lennith', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19459;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19459, 'Lisbeth', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19460;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19460, 'Lisette', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19461;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19461, 'Lynn', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19462;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19462, 'Magdelyn', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19463;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19463, 'Maira', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19464;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19464, 'Manja', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19465;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19465, 'Marguerite', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19466;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19466, 'Marisol', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19467;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19467, 'Marit', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19468;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19468, 'Meadow', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19469;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19469, 'Melodie', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19470;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19470, 'Millicent', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19471;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19471, 'Mistiana', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19472;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19472, 'Myrtha', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19473;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19473, 'Naima', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19474;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19474, 'Neranna', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19475;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19475, 'Odelle', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19476;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19476, 'Ophelia', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19477;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19477, 'Pacey', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19478;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19478, 'Rachael', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19479;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19479, 'Radmila', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19480;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19480, 'Rayna', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19481;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19481, 'Rebekka', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19482;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19482, 'Roberta', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19483;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19483, 'Roselle', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19484;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19484, 'Saige', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19485;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19485, 'Scarlet', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19486;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19486, 'Shancai', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19487;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19487, 'Shanna', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19488;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19488, 'Talia', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19489;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19489, 'Tasha', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19490;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19490, 'Valanese', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19491;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19491, 'Valeska', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19492;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19492, 'Vannah', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19493;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19493, 'Viridiana', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19494;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19494, 'Whittany', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19495;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19495, 'Wynna', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19496;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19496, 'Xara', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19497;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19497, 'Yarina', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19498;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19498, 'Zivanka', 23, 1);
DELETE FROM `namegen` WHERE `id` = 19499;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19499, 'Zoe', 23, 1);
