-- Gilnean race support

DELETE FROM `charhairgeosets` WHERE `id` = 631;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (631, 23 0, 0, 0, 1);
DELETE FROM `charhairgeosets` WHERE `id` = 632;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (632, 23 0, 1, 2, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 633;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (633, 23 0, 2, 3, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 634;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (634, 23 0, 3, 4, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 635;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (635, 23 0, 4, 5, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 636;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (636, 23 0, 5, 6, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 637;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (637, 23 0, 6, 7, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 638;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (638, 23 0, 7, 8, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 639;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (639, 23 0, 8, 9, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 640;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (640, 23 0, 9, 10, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 641;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (641, 23 0, 10, 11, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 642;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (642, 23 0, 11, 12, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 643;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (643, 23 1, 0, 2, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 644;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (644, 23 1, 1, 3, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 645;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (645, 23 1, 2, 4, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 646;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (646, 23 1, 3, 5, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 647;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (647, 23 1, 4, 6, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 648;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (648, 23 1, 5, 7, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 649;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (649, 23 1, 6, 8, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 650;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (650, 23 1, 7, 9, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 651;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (651, 23 1, 8, 10, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 652;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (652, 23 1, 9, 11, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 653;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (653, 23 1, 10, 12, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 654;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (654, 23 1, 11, 13, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 655;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (655, 23 1, 12, 14, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 656;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (656, 23 1, 13, 15, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 657;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (657, 23 1, 14, 16, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 658;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (658, 23 1, 15, 17, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 659;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (659, 23 1, 16, 18, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 660;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (660, 23 1, 17, 19, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 661;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (661, 23 1, 18, 20, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 662;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (662, 23 1, 19, 21, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 663;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (663, 23 1, 20, 22, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 664;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (664, 23 1, 21, 23, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 665;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (665, 23 1, 22, 24, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 666;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (666, 23 1, 23, 25, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 667;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (667, 23 0, 12, 13, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 668;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (668, 23 0, 13, 14, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 669;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (669, 23 0, 14, 15, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 670;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (670, 23 0, 15, 16, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 671;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (671, 23 0, 16, 17, 0);