-- [F-032] mod-maghar: skilllineability: 35 inserts, 61 updates, 0 deletes

-- New entries
DELETE FROM `skilllineability` WHERE `id` = 21981;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (21981, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 21982;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (21982, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 21983;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (21983, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 21984;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (21984, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 21985;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (21985, 790, 69042, 256, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 21986;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (21986, 790, 69045, 256, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 21987;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (21987, 790, 69046, 256, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 21988;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (21988, 790, 69070, 256, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 21989;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (21989, 790, 69041, 256, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31448;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31448, 790, 69044, 256, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31450;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31450, 756, 80866, 512, 1024, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31451;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31451, 756, 80867, 512, 1024, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31452;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31452, 756, 80868, 512, 1, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31453;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31453, 760, 80869, 1024, 1024, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31454;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31454, 760, 80870, 1024, 8, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31455;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31455, 760, 80871, 1024, 256, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31456;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31456, 760, 80872, 1024, 1024, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31457;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31457, 760, 80873, 1024, 8, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31458;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31458, 760, 80874, 1024, 256, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31459;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31459, 792, 110001, 8192, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31460;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31460, 792, 110002, 8192, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31461;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31461, 792, 110003, 8192, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31462;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31462, 792, 110004, 8192, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31463;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31463, 791, 110005, 4096, 1503, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31464;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31464, 791, 110006, 4096, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31465;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31465, 791, 110007, 4096, 32, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31466;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31466, 791, 110008, 4096, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31467;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31467, 791, 110009, 4096, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31468;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31468, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31469;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31469, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31470;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31470, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31471;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31471, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31472;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31472, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31473;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31473, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 31474;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (31474, 762, 33388, 0, 32, 0, 0, 1, 33391, 1, 0, 0, 0, 0);

-- Changed values
DELETE FROM `skilllineability` WHERE `id` = 590;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (590, 98, 668, 7245, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 592;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (592, 109, 669, 9138, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 727;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (727, 137, 813, 4608, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 3269;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (3269, 237, 3565, 7245, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 3270;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (3270, 237, 3562, 7245, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 3271;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (3271, 237, 3567, 946, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 3272;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (3272, 237, 3561, 7245, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 3273;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (3273, 237, 3566, 946, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 3274;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (3274, 237, 3563, 946, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 5989;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (5989, 237, 11419, 7245, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 5990;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (5990, 237, 11416, 7245, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 5991;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (5991, 237, 11417, 946, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 5992;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (5992, 237, 10059, 7245, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 5993;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (5993, 237, 11420, 946, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 5994;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (5994, 237, 11418, 946, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 7594;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (7594, 594, 13819, 7245, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 12518;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (12518, 594, 23214, 7245, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 13151;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (13151, 373, 2825, 946, 64, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 14013;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (14013, 756, 28730, 512, 470, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 14022;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (14022, 760, 6562, 1024, 47, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 14023;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (14023, 760, 28878, 1024, 1488, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 14779;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (14779, 184, 31801, 7245, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 14784;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (14784, 184, 31898, 946, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 14787;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (14787, 184, 31803, 16383, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 14788;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (14788, 184, 31804, 7245, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 14795;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (14795, 373, 32182, 7245, 64, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 14815;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (14815, 237, 32271, 7245, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 14816;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (14816, 237, 32272, 946, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 14817;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (14817, 237, 32266, 7245, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 14818;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (14818, 237, 32267, 946, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 15034;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (15034, 125, 33702, 2, 400, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 15035;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (15035, 125, 33697, 2, 1090, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 15040;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (15040, 237, 33690, 7245, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 15041;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (15041, 237, 33691, 7245, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 15252;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (15252, 594, 34767, 946, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 15253;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (15253, 594, 34769, 946, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 15606;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (15606, 237, 35715, 946, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 15607;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (15607, 237, 35717, 946, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 16999;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (16999, 237, 49359, 7245, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 17000;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (17000, 237, 49358, 946, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 17003;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (17003, 237, 49361, 946, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 17004;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (17004, 237, 49360, 7245, 128, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 17510;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (17510, 756, 50613, 512, 32, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 18299;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (18299, 184, 53726, 7245, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 18308;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (18308, 184, 53733, 946, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 18311;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (18311, 184, 53736, 946, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 18314;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (18314, 184, 53742, 946, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 20089;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (20089, 777, 23214, 7245, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 20090;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (20090, 777, 34767, 946, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 20091;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (20091, 777, 13819, 7245, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 20092;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (20092, 777, 34769, 946, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 20110;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (20110, 777, 55531, 946, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 20171;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (20171, 760, 59539, 1024, 32, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 20283;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (20283, 777, 60424, 7245, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 20289;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (20289, 202, 60867, 7245, 0, 0, 0, 1, 0, 0, 490, 480, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 20290;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (20290, 202, 60866, 946, 0, 0, 0, 1, 0, 0, 490, 480, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 20665;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (20665, 126, 21009, 8, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 20867;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (20867, 183, 63645, 16383, 1535, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 20868;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (20868, 183, 63644, 16383, 1535, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 21723;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (21723, 253, 75460, 16383, 8, 0, 0, 1, 0, 2, 0, 0, 0, 0);
DELETE FROM `skilllineability` WHERE `id` = 21724;
INSERT INTO `skilllineability` (`id`, `skill_line`, `spell_id`, `required_races`, `required_classes`, `excluded_races`, `excluded_classes`, `min_skill_value`, `spell_parent_id`, `acquire_method`, `skill_grey_level`, `skill_yellow_level`, `character_points_1`, `character_points_2`) VALUES (21724, 375, 75461, 16383, 64, 0, 0, 1, 0, 2, 0, 0, 0, 0);
