-- [F-032] mod-maghar: charhairgeosets: 25 inserts, 0 updates, 0 deletes

-- New entries
DELETE FROM `charhairgeosets` WHERE `id` = 606;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (606, 14, 0, 0, 0, 1);
DELETE FROM `charhairgeosets` WHERE `id` = 607;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (607, 14, 0, 1, 2, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 608;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (608, 14, 0, 2, 3, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 609;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (609, 14, 0, 3, 4, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 610;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (610, 14, 0, 4, 5, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 611;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (611, 14, 0, 5, 6, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 612;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (612, 14, 0, 6, 7, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 613;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (613, 14, 1, 0, 2, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 614;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (614, 14, 1, 1, 3, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 615;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (615, 14, 1, 2, 4, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 616;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (616, 14, 1, 3, 5, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 617;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (617, 14, 1, 4, 6, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 618;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (618, 14, 1, 5, 7, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 619;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (619, 14, 1, 6, 8, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 620;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (620, 14, 1, 7, 0, 1);
DELETE FROM `charhairgeosets` WHERE `id` = 621;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (621, 14, 1, 9, 10, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 622;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (622, 14, 1, 10, 11, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 623;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (623, 14, 1, 11, 12, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 624;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (624, 14, 1, 12, 13, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 625;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (625, 14, 0, 7, 8, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 626;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (626, 14, 0, 8, 9, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 627;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (627, 14, 0, 9, 10, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 628;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (628, 14, 0, 10, 11, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 629;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (629, 14, 0, 11, 12, 0);
DELETE FROM `charhairgeosets` WHERE `id` = 630;
INSERT INTO `charhairgeosets` (`id`, `race`, `gender`, `variation`, `geoset`, `show_scalp`) VALUES (630, 14, 1, 8, 9, 0);
