-- namegen: 24 inserts, 0 updates, 0 deletes

-- New entries
DELETE FROM `namegen` WHERE `id` = 19500;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19500, 'Grok', 15, 0);
DELETE FROM `namegen` WHERE `id` = 19501;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19501, 'Mogor', 15, 0);
DELETE FROM `namegen` WHERE `id` = 19502;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19502, 'Tharg', 15, 0);
DELETE FROM `namegen` WHERE `id` = 19503;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19503, 'Krol', 15, 0);
DELETE FROM `namegen` WHERE `id` = 19504;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19504, 'Gorlash', 15, 0);
DELETE FROM `namegen` WHERE `id` = 19505;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19505, 'Brugor', 15, 0);
DELETE FROM `namegen` WHERE `id` = 19506;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19506, 'Dorgok', 15, 0);
DELETE FROM `namegen` WHERE `id` = 19507;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19507, 'Krosh', 15, 0);
DELETE FROM `namegen` WHERE `id` = 19508;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19508, 'Grimnok', 15, 0);
DELETE FROM `namegen` WHERE `id` = 19509;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19509, 'Lunk', 15, 0);
DELETE FROM `namegen` WHERE `id` = 19510;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19510, 'Urok', 15, 0);
DELETE FROM `namegen` WHERE `id` = 19511;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19511, 'Zorbo', 15, 0);
DELETE FROM `namegen` WHERE `id` = 19512;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19512, 'Chogara', 15, 1);
DELETE FROM `namegen` WHERE `id` = 19513;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19513, 'Mogra', 15, 1);
DELETE FROM `namegen` WHERE `id` = 19514;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19514, 'Urda', 15, 1);
DELETE FROM `namegen` WHERE `id` = 19515;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19515, 'Grulla', 15, 1);
DELETE FROM `namegen` WHERE `id` = 19516;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19516, 'Zogra', 15, 1);
DELETE FROM `namegen` WHERE `id` = 19517;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19517, 'Karga', 15, 1);
DELETE FROM `namegen` WHERE `id` = 19518;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19518, 'Maghara', 15, 1);
DELETE FROM `namegen` WHERE `id` = 19519;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19519, 'Brogga', 15, 1);
DELETE FROM `namegen` WHERE `id` = 19520;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19520, 'Gorma', 15, 1);
DELETE FROM `namegen` WHERE `id` = 19521;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19521, 'Hargala', 15, 1);
DELETE FROM `namegen` WHERE `id` = 19522;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19522, 'Thokra', 15, 1);
DELETE FROM `namegen` WHERE `id` = 19523;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19523, 'Wulgra', 15, 1);
