-- skillraceclassinfo: 1 inserts, 119 updates, 0 deletes

-- New entries
DELETE FROM `skillraceclassinfo` WHERE `id` = 1142; -- ogre racials
INSERT INTO `skillraceclassinfo` (`id`, `skill_id`, `race_mask`, `class_mask`, `flags`, `min_level`, `skill_tier_id`, `skill_cost_id`) VALUES (1142, 793, 16384, 1535, 1170, 0, 0, 0);

-- Changed values
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 21;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 24;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 26;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 27;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384/*, `flags` = 128, `skill_tier_id` = 0*/ WHERE `id` = 28; -- look into this
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 29;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 30;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 34;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 35;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 36;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 37;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 38;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 41;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 43;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 45;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 47;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 48;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 51;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 54;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 59;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 62;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 64;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 65;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 66;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 73;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 76;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 79;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 81;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 83;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 84;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 85;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 88;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 91;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 93;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 97;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 104;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 105;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 106;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 108;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 111;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 112;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 113;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 117;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 126;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 137;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 145;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 146;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 147;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 148;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 149;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 151;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 155;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 158;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 159;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 175;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 178;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 183;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 186;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 189;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 191;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 193;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 198;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 200;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 203;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 204;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 205;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 241;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 243;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 244;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 246;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 265;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 266;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 268;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 269;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 270;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 271;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 272;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 281;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 282;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 284;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 328;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 330;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 403;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 441;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 442;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 443;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 464;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 481;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 622;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 628;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 629;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 630;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384/*, `class_mask` = (`class_mask` | 1) & ~4*/ WHERE `id` = 632;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384/*, `class_mask` = (`class_mask` | 4) & ~1*/ WHERE `id` = 634;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 635;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 637;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 638;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384/*, `class_mask` = (`class_mask` | 1) & ~1024*/ WHERE `id` = 642;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384/*, `class_mask` = (`class_mask` | 4) & ~1024*/ WHERE `id` = 644;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384/*, `class_mask` = `class_mask` | 32, `skill_tier_id` = 41*/ WHERE `id` = 742;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 781;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 865;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384/*, `class_mask` = `class_mask` & ~511, `flags` = 128, `skill_tier_id` = 0*/ WHERE `id` = 866;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 876;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 886;
UPDATE `skillraceclassinfo` SET `race_mask` = `race_mask` | 16384 WHERE `id` = 899;
