-- namegen: 24 inserts, 0 updates, 0 deletes

-- New entries
DELETE FROM `namegen` WHERE `id` = 19500;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19500, 'Grok', 15, 0);
DELETE FROM `namegen` WHERE `id` = 19501;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19501, 'Mogor', 15, 0);
DELETE FROM `namegen` WHERE `id` = 19502;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18996, 'Tharg', 15, 0);
DELETE FROM `namegen` WHERE `id` = 19503;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18997, 'Krol', 15, 0);
DELETE FROM `namegen` WHERE `id` = 19504;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18998, 'Gorlash', 15, 0);
DELETE FROM `namegen` WHERE `id` = 19505;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (18999, 'Brugor', 15, 0);
DELETE FROM `namegen` WHERE `id` = 19506;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19000, 'Dorgok', 15, 0);
DELETE FROM `namegen` WHERE `id` = 19507;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19001, 'Krosh', 15, 0);
DELETE FROM `namegen` WHERE `id` = 19508;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19002, 'Grimnok', 15, 0);
DELETE FROM `namegen` WHERE `id` = 19509;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19003, 'Lunk', 15, 0);
DELETE FROM `namegen` WHERE `id` = 19510;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19004, 'Urok', 15, 0);
DELETE FROM `namegen` WHERE `id` = 19511;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19005, 'Zorbo', 15, 0);
DELETE FROM `namegen` WHERE `id` = 19512;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19006, 'Chogara', 15, 1);
DELETE FROM `namegen` WHERE `id` = 19513;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19007, 'Mogra', 15, 1);
DELETE FROM `namegen` WHERE `id` = 19514;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19008, 'Urda', 15, 1);
DELETE FROM `namegen` WHERE `id` = 19515;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19009, 'Grulla', 15, 1);
DELETE FROM `namegen` WHERE `id` = 19516;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19010, 'Zogra', 15, 1);
DELETE FROM `namegen` WHERE `id` = 19517;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19011, 'Karga', 15, 1);
DELETE FROM `namegen` WHERE `id` = 19518;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19012, 'Maghara', 15, 1);
DELETE FROM `namegen` WHERE `id` = 19519;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19013, 'Brogga', 15, 1);
DELETE FROM `namegen` WHERE `id` = 19520;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19014, 'Gorma', 15, 1);
DELETE FROM `namegen` WHERE `id` = 19521;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19015, 'Hargala', 15, 1);
DELETE FROM `namegen` WHERE `id` = 19522;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19016, 'Thokra', 15, 1);
DELETE FROM `namegen` WHERE `id` = 19523;
INSERT INTO `namegen` (`id`, `name`, `race_id`, `sex`) VALUES (19017, 'Wulgra', 15, 1);
